#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "ESP32-S31-CHATBOT"
#endif

#ifndef MICROPY_HW_MCU_NAME
#define MICROPY_HW_MCU_NAME "ESP32S31"
#endif

#define MICROPY_HW_USB_PRODUCT_FS_STRING "ESP-VISION " MICROPY_HW_BOARD_NAME

/* The board exposes USJ only; disable the unconnected USB-OTG device port. */
#define MICROPY_HW_ENABLE_USBDEV (0)
#define MICROPY_HW_ESP_USB_SERIAL_JTAG (1)

#define MICROPY_PY_ESPNOW (0)
#define MICROPY_HW_ENABLE_SDCARD (0)
#define MICROPY_PY_BLUETOOTH (0)
#define MICROPY_PY_MACHINE_ADC (0)
#define MICROPY_PY_MACHINE_ADC_BLOCK (0)

#ifndef MICROPY_PY_NETWORK_WLAN
#define MICROPY_PY_NETWORK_WLAN (1)
#endif

#define MICROPY_HW_I2C0_SCL (1)
#define MICROPY_HW_I2C0_SDA (0)
